# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about_me', models.TextField()),
                ('qualifications', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('concession', models.BooleanField()),
                ('client_types', models.ManyToManyField(to='profiles.ClientTypes')),
                ('consultation_types', models.ManyToManyField(to='profiles.ConsultationTypes')),
                ('counselling_areas', models.ManyToManyField(to='profiles.CounsellingAreas')),
            ],
        ),
    ]
