# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170709_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationTypes',
            new_name='ClientType',
        ),
        migrations.RenameModel(
            old_name='CounsellingAreas',
            new_name='ConsultationType',
        ),
        migrations.RenameModel(
            old_name='ClientTypes',
            new_name='CounsellingArea',
        ),
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
