# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170709_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client_types',
        ),
        migrations.AddField(
            model_name='profile',
            name='client_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='consultation_types',
        ),
        migrations.AddField(
            model_name='profile',
            name='consultation_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='counselling_areas',
        ),
        migrations.AddField(
            model_name='profile',
            name='counselling_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='ConsultationType',
        ),
        migrations.DeleteModel(
            name='CounsellingArea',
        ),
    ]
