# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 19:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170709_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='concession',
        ),
        migrations.AddField(
            model_name='profile',
            name='concessions_availible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=profiles.models.empty, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='consultation_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=profiles.models.empty, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='counselling_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=profiles.models.empty, size=None),
        ),
    ]
