# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170709_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=profiles.models.empty, size=None),
        ),
    ]
